import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  ContainerBuilder,
  EmbedBuilder,
  SectionBuilder,
  ThumbnailBuilder,
  type InteractionReplyOptions,
  MessageFlags,
} from "discord.js";
import { emojis } from "../../emojis.js";
import { embedColors } from "../../lib/embeds.js";
import { customEmoji, emojiAssetUrl } from "../../lib/custom-emoji.js";
import { formatChannel, formatUser } from "../../lib/formatters.js";
import { divider, textBlock, v2Flags } from "../../lib/v2.js";
import { escapeDiscord, roundTitle } from "../room/labels.js";

type Tone = "success" | "error" | "info" | "warn";

function toneColor(tone: Tone): number {
  if (tone === "success") {
    return embedColors.success;
  }
  if (tone === "error") {
    return embedColors.error;
  }
  if (tone === "warn") {
    return 0xe67e22;
  }
  return embedColors.info;
}

function toneEmoji(tone: Tone): string {
  if (tone === "success") {
    return emojis.success;
  }
  if (tone === "error") {
    return emojis.error;
  }
  return emojis.info;
}

function linesEmbed(color: number, lines: string[]): EmbedBuilder {
  const [title, ...rest] = lines;
  return new EmbedBuilder().setColor(color).setTitle(title ?? "Bracket").setDescription(rest.filter((line) => line.trim()).join("\n") || null);
}

export function bracketPanel(
  tone: Tone,
  title: string,
  lines: string[],
  ephemeral = true,
): InteractionReplyOptions {
  const body = [title, ...lines.filter((line) => line.trim())];
  return {
    embeds: [linesEmbed(toneColor(tone), [`${toneEmoji(tone)} ${body[0]}`, ...body.slice(1)])],
    flags: ephemeral ? MessageFlags.Ephemeral : undefined,
    allowedMentions: { parse: [] },
  };
}

function uploadCard(color: number, title: string, body: string, footer: string, thumbnailUrl?: string | null): InteractionReplyOptions {
  const section = new SectionBuilder().addTextDisplayComponents(
    textBlock(`# ${title}`),
    textBlock(body),
    textBlock(`-# ${footer}`),
  );
  if (thumbnailUrl) {
    section.setThumbnailAccessory(new ThumbnailBuilder().setURL(thumbnailUrl));
  }
  return {
    components: [new ContainerBuilder().setAccentColor(color).addSectionComponents(section)],
    flags: v2Flags,
    allowedMentions: { parse: [] },
  };
}

export function matchUpdatedMessage(input: {
  tournamentName: string;
  leftName: string;
  rightName: string;
  score1: number;
  score2: number;
  winnerName: string;
  channelId: string;
  actorTag: string;
  avatarUrl: string;
  note?: string | null;
}): InteractionReplyOptions {
  const lines = [
    `${emojis.challonge} The match has been updated with the following details:`,
    `${emojis.torneo} **Tournament:** ${escapeDiscord(input.tournamentName)}`,
    `${emojis.vs} **Match:** ${escapeDiscord(input.leftName)} vs ${escapeDiscord(input.rightName)}`,
    `${emojis.scoreboard} **Score:** \`${input.score1} - ${input.score2}\``,
    `${emojis.winner} **Winner:** ${escapeDiscord(input.winnerName)}`,
    `${emojis.textChannel} **Channel:** ${formatChannel(null, input.channelId)}`,
  ];
  if (input.note?.trim()) {
    lines.push(`${emojis.info} **Note:** ${escapeDiscord(input.note.trim())}`);
  }
  return uploadCard(
    0xe67e22,
    `${emojis.success} Match Updated Successfully`,
    lines.join("\n"),
    `Updated by ${input.actorTag}`,
    input.avatarUrl,
  );
}

export function channelClosedMessage(actorId: string, actorTag: string): InteractionReplyOptions {
  return uploadCard(
    embedColors.info,
    `${emojis.success} Channel Closed Successfully`,
    [
      `${emojis.channels} This channel has been closed and moved to the archived category.`,
      `${emojis.members} **Staff Responsible:** ${formatUser(actorId)} (\`${actorTag}\`)`,
    ].join("\n"),
    `Closed by ${actorTag}`,
    emojiAssetUrl(emojis.open_close),
  );
}

export function transcriptGeneratedMessage(transcriptUrl: string, actorTag: string): InteractionReplyOptions {
  return uploadCard(
    embedColors.success,
    `${emojis.success} Transcript generated`,
    [
      `${emojis.transcript} A transcript has been generated.`,
      `${emojis.link} **View transcript:** [Click here](${transcriptUrl})`,
    ].join("\n"),
    `Generated by ${actorTag}`,
    emojiAssetUrl(emojis.transcript_thumnail),
  );
}

export function scoreCorrectedMessage(input: {
  tournamentName: string;
  leftName: string;
  rightName: string;
  oldScore1: number | null;
  oldScore2: number | null;
  score1: number;
  score2: number;
  winnerName: string;
  rebuilt: number;
  actorTag: string;
}): InteractionReplyOptions {
  const before =
    input.oldScore1 != null && input.oldScore2 != null ? `\`${input.oldScore1} - ${input.oldScore2}\`` : "*Unknown*";
  const lines = [
    `${emojis.torneo} **Tournament:** ${escapeDiscord(input.tournamentName)}`,
    `${emojis.vs} **Match:** ${escapeDiscord(input.leftName)} vs ${escapeDiscord(input.rightName)}`,
    `${emojis.scoreboard} **Score:** ${before} → \`${input.score1} - ${input.score2}\``,
    `${emojis.winner} **Winner:** ${escapeDiscord(input.winnerName)}`,
  ];
  if (input.rebuilt > 0) {
    lines.push(
      `${emojis.alert} **Rooms rebuilt:** **${input.rebuilt}** invalid ticket${input.rebuilt === 1 ? "" : "s"} removed and open matches reopened with the correct captains.`,
    );
  }
  const section = new SectionBuilder().addTextDisplayComponents(
    textBlock(`# ${emojis.success} Bracket Corrected Successfully`),
    textBlock(lines.join("\n")),
    textBlock(`-# Corrected by \`${input.actorTag}\``),
  );
  const logo = emojiAssetUrl(emojis.challonge);
  if (logo) {
    section.setThumbnailAccessory(new ThumbnailBuilder().setURL(logo));
  }
  return {
    components: [new ContainerBuilder().setAccentColor(embedColors.success).addSectionComponents(section)],
    flags: v2Flags,
    allowedMentions: { parse: [] },
  };
}

function simpleCard(color: number, title: string, body: string, footer?: string): InteractionReplyOptions {
  const blocks = [textBlock(`# ${title}`), textBlock(body)];
  if (footer) {
    blocks.push(textBlock(`-# ${footer}`));
  }
  return {
    components: [new ContainerBuilder().setAccentColor(color).addTextDisplayComponents(blocks)],
    flags: v2Flags,
    allowedMentions: { parse: [] },
  };
}

export function bracketNotice(tone: Tone, title: string, lines: string[]): InteractionReplyOptions {
  return simpleCard(toneColor(tone), `${toneEmoji(tone)} ${title}`, lines.filter((line) => line.trim()).join("\n"));
}

export function correctionCancelledMessage(): InteractionReplyOptions {
  return simpleCard(
    embedColors.info,
    `${emojis.info} Correction cancelled`,
    "No tickets were deleted and the bracket was left unchanged.",
  );
}

export type CorrectTicket = {
  channelId: string;
  round: number | null;
  group: string | null;
  leftName: string;
  rightName: string;
  status: string;
};

function ticketStage(ticket: CorrectTicket): string {
  const round = ticket.round == null ? "Round unknown" : roundTitle(ticket.round);
  return ticket.group ? `Group ${escapeDiscord(ticket.group)} · ${round}` : round;
}

function ticketLines(tickets: CorrectTicket[]): string {
  const shown = tickets.slice(0, 12);
  const blocks = shown.map((ticket) => {
    const status = ticket.status === "closed" ? "Closed" : "Open";
    return [
      `> **Channel:** ${formatChannel(null, ticket.channelId)}`,
      `> **Round:** ${ticketStage(ticket)}`,
      `> **Status:** **${status}**`,
    ].join("\n");
  });
  const hidden = tickets.length - shown.length;
  if (hidden > 0) {
    blocks.push(`> *and **${hidden}** more*`);
  }
  return blocks.join("\n\n");
}

export function correctConfirmCustomId(
  action: "ok" | "no",
  userId: string,
  tournamentId: string,
  matchId: number,
  score1: number,
  score2: number,
): string {
  return `bracket:correct:${action}:${userId}:${tournamentId}:${matchId}:${score1}:${score2}`;
}

export function parseCorrectConfirmCustomId(customId: string): {
  action: "ok" | "no";
  userId: string;
  tournamentId: string;
  matchId: number;
  score1: number;
  score2: number;
} | null {
  const parts = customId.split(":");
  if (parts.length !== 8 || parts[0] !== "bracket" || parts[1] !== "correct") {
    return null;
  }
  const action = parts[2];
  if (action !== "ok" && action !== "no") {
    return null;
  }
  const userId = parts[3] ?? "";
  const tournamentId = parts[4] ?? "";
  const matchId = Number(parts[5]);
  const score1 = Number(parts[6]);
  const score2 = Number(parts[7]);
  if (!/^\d{17,20}$/.test(userId) || !/^[a-f0-9]{24}$/i.test(tournamentId)) {
    return null;
  }
  if (![matchId, score1, score2].every((value) => Number.isInteger(value) && value >= 0)) {
    return null;
  }
  return { action, userId, tournamentId, matchId, score1, score2 };
}

export function correctConfirmMessage(input: {
  tournamentName: string;
  leftName: string;
  rightName: string;
  oldScore1: number | null;
  oldScore2: number | null;
  score1: number;
  score2: number;
  winnerName: string;
  tickets: CorrectTicket[];
  actorTag: string;
  userId: string;
  tournamentId: string;
  matchId: number;
}): InteractionReplyOptions {
  const count = input.tickets.length;
  const previous =
    input.oldScore1 != null && input.oldScore2 != null
      ? `\`${input.oldScore1} - ${input.oldScore2}\` → \`${input.score1} - ${input.score2}\``
      : `\`${input.score1} - ${input.score2}\``;
  const header = new SectionBuilder().addTextDisplayComponents(
    textBlock(`# ${emojis.alert} Confirm bracket correction`),
    textBlock(
      `The winner of **${escapeDiscord(input.leftName)} vs ${escapeDiscord(input.rightName)}** would change. Review the tickets below before accepting. Nothing is changed until you do.`,
    ),
  );
  const logo = emojiAssetUrl(emojis.challonge);
  if (logo) {
    header.setThumbnailAccessory(new ThumbnailBuilder().setURL(logo));
  }

  const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder()
      .setCustomId(
        correctConfirmCustomId("ok", input.userId, input.tournamentId, input.matchId, input.score1, input.score2),
      )
      .setLabel("Aceptar")
      .setStyle(ButtonStyle.Success)
      .setEmoji(customEmoji(emojis.success)),
    new ButtonBuilder()
      .setCustomId(
        correctConfirmCustomId("no", input.userId, input.tournamentId, input.matchId, input.score1, input.score2),
      )
      .setLabel("Cancelar")
      .setStyle(ButtonStyle.Secondary)
      .setEmoji(customEmoji(emojis.error)),
  );

  return {
    components: [
      new ContainerBuilder()
        .setAccentColor(0xe67e22)
        .addSectionComponents(header)
        .addSeparatorComponents(divider())
        .addTextDisplayComponents(
          textBlock(
            [
              `## ${emojis.challonge} Proposed correction`,
              `${emojis.torneo} **Tournament:** ${escapeDiscord(input.tournamentName)}`,
              `${emojis.vs} **Match:** ${escapeDiscord(input.leftName)} vs ${escapeDiscord(input.rightName)}`,
              `${emojis.scoreboard} **Score:** ${previous}`,
              `${emojis.winner} **New winner:** ${escapeDiscord(input.winnerName)}`,
            ].join("\n"),
          ),
        )
        .addSeparatorComponents(divider())
        .addTextDisplayComponents(
          textBlock(
            [
              `## ${emojis.textChannel} Tickets that will be deleted`,
              `**${count}** ticket${count === 1 ? "" : "s"} created from the current winner.`,
              "",
              ticketLines(input.tickets),
            ].join("\n"),
          ),
        )
        .addSeparatorComponents(divider())
        .addTextDisplayComponents(
          textBlock(
            [
              `## ${emojis.alert} If you accept`,
              "> Those tickets are **deleted**, including their schedules.",
              "> Their scores on Challonge are **reset**.",
              "> Matches that open again are **recreated** with the correct captains.",
              "> Matches still waiting on a winner stay closed until that round is ready.",
              "> **Cancelar** leaves the bracket and every ticket unchanged.",
            ].join("\n"),
          ),
          textBlock(`-# Only \`${input.actorTag}\` can confirm this correction.`),
        )
        .addActionRowComponents(row),
    ],
    flags: v2Flags,
    allowedMentions: { parse: [] },
  };
}
